### ISSUE TITLE
Grape requests not showing in 'Requests Analysis' page

### ISSUE THREAD

**Issue by JeroenRijks** [igorkasyanchuk/rails_performance#55]
Hi,

I've configured this in my API, which uses Grape to manage most endpoints. Individual requests sent to grape endpoints are shown under `/rails/performance/grape`, but these grape endpoints aren't shown under `/rails/performance/requests`. Is this intended functionality at this stage, or is something misconfigured on my side or in the gem?

I'm trying to find out how frequently each of my endpoints are being hit, which I would be able to do with the `Requests` column of the `/requests` page.

Versions:
- rails_performance: 1.2.0 
- grape: 1.7.1
- redis: 4.8.1

Thanks!

**Comment by igorkasyanchuk** [comment]
As I remember I store grape requests separately (because of different structures and events). So it won't appear if not appears right now.

https://github.com/igorkasyanchuk/rails_performance/blob/master/lib/rails_performance/data_source.rb#L61 here is an example

if you want just make a fork and make a custom version for you.

**Comment by JeroenRijks** [comment]
Ok, thank you for the gem and the fast reply 👍
